
services:

  mysql:
    image: mysql:9.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - ./mysql/db:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./wp:/app

  phpmyadmin:
    image: phpmyadmin:5.2.2
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    ports:
      - 8081:80

  nginx:
    image: nginx:1.28.0
    depends_on:
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./wp:/app
    ports:
      - 8080:80


